version: '3'

services:
  web:
    build: .
    container_name: php_web
    depends_on:
      - database
    ports:
      - "80:80"
    stdin_open: true
    links: 
      - database
    tty: true
  database:
    image: mariadb:11.5
    container_name: database
    hostname: database 
    restart: unless-stopped
    expose:
      - 3306
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
      MYSQL_DATABASE: "passboltdb"
      MYSQL_USER: "passbolt"
      MYSQL_PASSWORD: "P4ssb0lt"
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d